version: '2'

services:
    front:
        build: ./front-service
        container_name: front
        image: front
        links:
            - front-ui
            - aiapi
        ports:
            - "80:80"
    front-ui:
        build: ./front-ui-service
        container_name: front-ui
        image: front-ui
        expose:
            - "8080"
    aiapi:
        build: ./aiapi-service
        container_name: aiapi
        image: aiapi
        expose:
            - "8000"
